# 远程配置文件，用于动态调整部分配置

# 新增的服务器IP列表
server_ip_list = []

# 是否启用卡密界面
enable_card_secret = true
# 是否启用直接购买界面
enable_pay_directly = true
# 是否优先展示卡密界面（设置为false时则优先显示直接购买界面）
show_card_secret_first = false

# 新增的黑名单
#[[black_list]]
## 封禁于
#ban_at = "2020-01-01"
## QQ
#qq = "1234"
## 昵称
#nickname = "拉黑"
## 原因
#reason = "测试拉黑"
